<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    //Metodo para obtener todos los post de una categoria
    public function findByCategory($category){
        return $this->getEntityManager()
            ->createQuery(
            'SELECT p FROM AppBundle:Post p WHERE p.categoria = :categoria ORDER BY p.id DESC')
            ->setParameter('categoria', $category)
            ->getResult();
    }

    //Metodo para obtener todos los posts
/*    public function obtenerPostsPaginados(){
        $queryBuilder = $this->createQueryBuilder('p')
            ->where('c.id = :categoriaId')
        ;
        return $queryBuilder->getQuery()->getResult();
    }*/

}
