services:
    app.admin.categoria:
        class: AppBundle\Admin\CategoriaAdmin
        arguments: [~, AppBundle\Entity\Categoria, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Categoria }
        public: true

    app.admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Post }
        public: true
